create table sensor
(
    id   int generated by default as identity PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);

create table measurements
(
    id         int generated by default as identity PRIMARY KEY,
    sensor_id  int references sensor (id),
    value      float check ( value > -100 AND value < 100 ),
    raining    boolean NOT NULL,
    created_at timestamp
);